### PR TITLE
Implement Fauna database interaction

### LINKED ISSUE #4: Add multiplayer functionality
Use an online database service to provide realtime multiplayer gameplay ability.

### PR DESCRIPTION
**Pull request by Nixinova**
Implement online mode using FaunaDB and Netlify Functions.

This PR just sets up the database; actually implementing multiplayer will come in a later PR.

Part of #4.

### CODE REVIEW

**Comment by Nixinova** [comment]
URL for testing: https://deploy-preview-8--carbonchess.netlify.app/.netlify/functions/database?type=

**Comment by Nixinova** [comment]
URL for testing: https://deploy-preview-8--carbonchess.netlify.app/.netlify/functions/database?type=

**Comment by Nixinova** [comment]
Lambda function is complete, just needs to be actually implemented now.

**Comment by Nixinova** [comment]
Changed this PR to just be about setting up the database; actually implementing multiplayer will come later.

**Review by adityatendulkar — APPROVED** [review]

**Comment by Nixinova** [comment]
Being fully implemented with PR #10.

**Pull request merged**
