### PR TITLE
Implement FenFurnace to control piece movement

### LINKED ISSUE #5: Revamp movement validation engine
Create move positions from FENs only instead of the current method based on moving pieces on the actual HTML chess board.

### LINKED ISSUE #7: Putting the king in check undoes the move
Whenever you move to check the king or do a move that the king can move into check from, the game undoes the last move but doesn't re-do it.

Could possibly be fixed anyway with the introduction of CheckApe (#5).

### PR DESCRIPTION
**Pull request by Nixinova**
Adds [FenFurnace](https://github.com/CarbonChess/FenFurnace) to control piece movement validation.

Replaces the entire validation script with the FenFurnace API.

Resolves #5 and fixes #7.

### CODE REVIEW

**Comment by Nixinova** [comment]
Mostly implemented: try at https://fenfurnace--carbonchess.netlify.app/play

**Comment by Nixinova** [comment]
"rnbqkbnr/ppp1pppp/8/1B2p3/8/8/PPPP1PPP/RNBQK1NR b KQkq - 1 3"

**Comment by Nixinova** [comment]
Almost ready

**Review by adityatendulkar — APPROVED** [review]
Very nice.

**Comment by Nixinova** [comment]
GitHub doesn't seem to be loading the last two commits...

**Pull request merged**
